import { colors, borderRadius, shadows } from "../../../styles/theme";

export const partiesStyle = (mobileView) => ({
  top: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    flexWrap: "wrap",
    gap: "16px",
  },
  heading: {
    fontSize: "24px",
    fontWeight: 700,
    color: colors.textPrimary,
    letterSpacing: "-0.5px",
  },
  button: {
    backgroundColor: colors.primary,
    color: colors.surface,
    fontWeight: 600,
    padding: mobileView ? "6px 12px" : "8px 20px",
    textTransform: "none",
    "&:hover": {
      backgroundColor: colors.primaryDark,
    },
  },
  partiesContainer: {
    width: "100%",
  },
  loadingCont: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    padding: "40px",
  },
  noPartiesCont: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    padding: "40px",
  },
  noPartiesText: {
    color: colors.textSecondary,
    fontSize: "16px",
  },
  partyCont: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      sm: "1fr 1fr",
      md: "1fr 1fr 1fr",
    },
    gap: "20px",
  },
  partyCard: {
    backgroundColor: colors.surface,
    padding: "24px",
    borderRadius: borderRadius.lg,
    boxShadow: shadows.sm,
    border: `1px solid ${colors.border}`,
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    "&:hover": {
      transform: "translateY(-4px)",
      boxShadow: shadows.md,
    },
  },
  name: {
    fontSize: "18px",
    fontWeight: 700,
    color: colors.textPrimary,
  },
  chipBuyer: {
    alignSelf: "flex-start",
    backgroundColor: colors.infoLight,
    color: colors.infoDark,
    padding: "4px 12px",
    borderRadius: borderRadius.full,
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  chipMiller: {
    alignSelf: "flex-start",
    backgroundColor: colors.warningLight,
    color: colors.warningDark,
    padding: "4px 12px",
    borderRadius: borderRadius.full,
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  phone: {
    fontSize: "14px",
    color: colors.textSecondary,
    marginTop: "8px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  detailButton: {
    marginTop: "auto",
    paddingTop: "16px",
    alignSelf: "flex-start",
    color: colors.primary,
    fontWeight: 600,
    textTransform: "none",
    "&:hover": {
      backgroundColor: "transparent",
      textDecoration: "underline",
    },
  },
});
