import { colors, borderRadius, shadows } from "../../styles/theme";

export const receiptStyles = () => ({
  receiptWrapper: {
    backgroundColor: colors.white,
    padding: "32px",
    borderRadius: borderRadius.md,
    color: colors.textPrimary,
    fontFamily: "'Roboto', 'Segoe UI', Tahoma, sans-serif",
    position: "relative",
    border: `1px solid ${colors.border}`,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottom: `2px solid ${colors.primary}`,
    paddingBottom: "16px",
    marginBottom: "20px",
  },
  companyName: {
    fontSize: "24px",
    fontWeight: 900,
    color: colors.primary,
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  companyTagline: {
    fontSize: "12px",
    color: colors.textSecondary,
    marginTop: "2px",
  },
  receiptTitle: {
    fontSize: "20px",
    fontWeight: 800,
    color: colors.textPrimary,
    textAlign: "right",
    textTransform: "uppercase",
  },
  receiptMeta: {
    textAlign: "right",
    fontSize: "12px",
    color: colors.textSecondary,
    marginTop: "4px",
  },
  infoSection: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "20px",
    backgroundColor: colors.surfaceMuted,
    padding: "16px",
    borderRadius: borderRadius.md,
  },
  infoCol: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  infoLabel: {
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase",
    color: colors.textSecondary,
  },
  infoValue: {
    fontSize: "15px",
    fontWeight: 700,
    color: colors.textPrimary,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginBottom: "20px",
    "& th": {
      backgroundColor: colors.primary,
      color: colors.white,
      padding: "10px 12px",
      fontSize: "12px",
      fontWeight: 700,
      textAlign: "left",
      textTransform: "uppercase",
    },
    "& td": {
      padding: "10px 12px",
      fontSize: "13px",
      borderBottom: `1px solid ${colors.border}`,
    },
  },
  summaryContainer: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: "24px",
  },
  summaryBox: {
    width: "280px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    backgroundColor: colors.surfaceMuted,
    padding: "16px",
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.border}`,
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "13px",
  },
  summaryTotalRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "16px",
    fontWeight: 900,
    borderTop: `2px solid ${colors.border}`,
    paddingTop: "8px",
    marginTop: "4px",
    color: colors.primary,
  },
  footer: {
    borderTop: `1px solid ${colors.border}`,
    paddingTop: "20px",
    marginTop: "20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  signBlock: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    width: "160px",
  },
  signLine: {
    width: "100%",
    borderBottom: `1px dashed ${colors.textSecondary}`,
    marginBottom: "4px",
  },
  signLabel: {
    fontSize: "11px",
    color: colors.textSecondary,
    fontWeight: 600,
  },
  paidStamp: {
    border: `3px solid ${colors.success}`,
    color: colors.success,
    fontWeight: 900,
    fontSize: "18px",
    textTransform: "uppercase",
    padding: "4px 16px",
    borderRadius: borderRadius.md,
    transform: "rotate(-8deg)",
    letterSpacing: "2px",
    display: "inline-block",
  },
  partialStamp: {
    border: `3px solid ${colors.warningDark}`,
    color: colors.warningDark,
    fontWeight: 900,
    fontSize: "18px",
    textTransform: "uppercase",
    padding: "4px 16px",
    borderRadius: borderRadius.md,
    transform: "rotate(-8deg)",
    letterSpacing: "2px",
    display: "inline-block",
  },
  unpaidStamp: {
    border: `3px solid ${colors.error}`,
    color: colors.error,
    fontWeight: 900,
    fontSize: "18px",
    textTransform: "uppercase",
    padding: "4px 16px",
    borderRadius: borderRadius.md,
    transform: "rotate(-8deg)",
    letterSpacing: "2px",
    display: "inline-block",
  },
});
