import { colors, borderRadius, shadows } from "../../styles/theme";

export const receiptStyles = () => ({
  receiptWrapper: {
    backgroundColor: colors.white,
    padding: { xs: "16px", sm: "32px" },
    borderRadius: borderRadius.md,
    color: colors.textPrimary,
    fontFamily: "'Roboto', 'Segoe UI', Tahoma, sans-serif",
    position: "relative",
    border: `1px solid ${colors.border}`,
    overflowX: "hidden",
    boxSizing: "border-box",
    width: "100%",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: "12px",
    borderBottom: `2px solid ${colors.primary}`,
    paddingBottom: "16px",
    marginBottom: "20px",
  },
  companyName: {
    fontSize: { xs: "18px", sm: "24px" },
    fontWeight: 900,
    color: colors.primary,
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  companyTagline: {
    fontSize: { xs: "10px", sm: "12px" },
    color: colors.textSecondary,
    marginTop: "2px",
  },
  receiptTitle: {
    fontSize: { xs: "15px", sm: "20px" },
    fontWeight: 800,
    color: colors.textPrimary,
    textAlign: "right",
    textTransform: "uppercase",
  },
  receiptMeta: {
    textAlign: "right",
    fontSize: { xs: "11px", sm: "12px" },
    color: colors.textSecondary,
    marginTop: "4px",
  },
  infoSection: {
    display: "flex",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "12px",
    marginBottom: "20px",
    backgroundColor: colors.surfaceMuted,
    padding: { xs: "12px", sm: "16px" },
    borderRadius: borderRadius.md,
  },
  infoCol: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    flex: "1 1 140px",
    minWidth: "130px",
  },
  infoLabel: {
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase",
    color: colors.textSecondary,
  },
  infoValue: {
    fontSize: { xs: "13px", sm: "15px" },
    fontWeight: 700,
    color: colors.textPrimary,
  },
  tableWrapper: {
    width: "100%",
    overflowX: "auto",
    marginBottom: "20px",
    WebkitOverflowScrolling: "touch",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "380px",
    "& th": {
      backgroundColor: colors.primary,
      color: colors.white,
      padding: "8px 10px",
      fontSize: "11px",
      fontWeight: 700,
      textAlign: "left",
      textTransform: "uppercase",
      whiteSpace: "nowrap",
    },
    "& td": {
      padding: "8px 10px",
      fontSize: "12px",
      borderBottom: `1px solid ${colors.border}`,
    },
  },
  summaryContainer: {
    display: "flex",
    justifyContent: "flex-end",
    marginBottom: "24px",
  },
  summaryBox: {
    width: { xs: "100%", sm: "280px" },
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    backgroundColor: colors.surfaceMuted,
    padding: { xs: "12px", sm: "16px" },
    borderRadius: borderRadius.md,
    border: `1px solid ${colors.border}`,
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "13px",
  },
  summaryTotalRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: { xs: "14px", sm: "16px" },
    fontWeight: 900,
    borderTop: `2px solid ${colors.border}`,
    paddingTop: "8px",
    marginTop: "4px",
    color: colors.primary,
  },
  footer: {
    borderTop: `1px solid ${colors.border}`,
    paddingTop: "20px",
    marginTop: "20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    flexWrap: "wrap",
    gap: "16px",
  },
  signBlock: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    width: { xs: "120px", sm: "160px" },
    minWidth: "100px",
  },
  signLine: {
    width: "100%",
    borderBottom: `1px dashed ${colors.textSecondary}`,
    marginBottom: "4px",
  },
  signLabel: {
    fontSize: "10px",
    color: colors.textSecondary,
    fontWeight: 600,
    textAlign: "center",
  },
  paidStamp: {
    border: `3px solid ${colors.success}`,
    color: colors.success,
    fontWeight: 900,
    fontSize: "18px",
    textTransform: "uppercase",
    padding: "4px 16px",
    borderRadius: borderRadius.md,
    transform: "rotate(-8deg)",
    letterSpacing: "2px",
    display: "inline-block",
  },
  partialStamp: {
    border: `3px solid ${colors.warningDark}`,
    color: colors.warningDark,
    fontWeight: 900,
    fontSize: "18px",
    textTransform: "uppercase",
    padding: "4px 16px",
    borderRadius: borderRadius.md,
    transform: "rotate(-8deg)",
    letterSpacing: "2px",
    display: "inline-block",
  },
  unpaidStamp: {
    border: `3px solid ${colors.error}`,
    color: colors.error,
    fontWeight: 900,
    fontSize: "18px",
    textTransform: "uppercase",
    padding: "4px 16px",
    borderRadius: borderRadius.md,
    transform: "rotate(-8deg)",
    letterSpacing: "2px",
    display: "inline-block",
  },
  itemList: {
  display: "flex",
  flexDirection: "column",
  gap: "8px",
  marginBottom: "20px",
},

itemRow: {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: "12px",
  padding: { xs: "10px 12px", sm: "12px 16px" },
  backgroundColor: colors.surfaceMuted,
  borderRadius: borderRadius.md,
  border: `1px solid ${colors.border}`,
  flexWrap: "wrap",
},

itemLabel: {
  fontSize: { xs: "11px", sm: "12px" },
  fontWeight: 700,
  color: colors.textSecondary,
  textTransform: "uppercase",
},

itemValue: {
  fontSize: { xs: "12px", sm: "14px" },
  fontWeight: 700,
  color: colors.textPrimary,
  textAlign: "right",
  wordBreak: "break-word",
},

sectionTitle: {
  fontSize: { xs: "13px", sm: "15px" },
  fontWeight: 800,
  color: colors.textPrimary,
  marginBottom: "10px",
  textTransform: "uppercase",
},
});
