import { colors, borderRadius, shadows } from "../../../../styles/theme";

export const addStockStyle = () => ({
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    paddingBottom: "40px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heading: {
    fontSize: "24px",
    fontWeight: 700,
    color: colors.textPrimary,
    letterSpacing: "-0.5px",
  },
  formLayout: {
    display: "flex",
    flexDirection: { xs: "column", lg: "row" },
    gap: "24px",
    alignItems: "flex-start",
  },
  formSection: {
    flex: { xs: 1, lg: 2 },
    backgroundColor: colors.surface,
    padding: "24px",
    borderRadius: borderRadius.lg,
    boxShadow: shadows.sm,
    border: `1px solid ${colors.border}`,
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: colors.textPrimary,
    marginBottom: "16px",
    borderBottom: `1px solid ${colors.border}`,
    paddingBottom: "8px",
  },
  gridRow: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr" },
    gap: "16px",
  },
  summarySection: {
    flex: { xs: 1, lg: 1 },
    backgroundColor: colors.surface,
    padding: "24px",
    borderRadius: borderRadius.lg,
    boxShadow: shadows.md,
    border: `1px solid ${colors.secondary}`,
    position: "sticky",
    top: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  summaryTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: colors.secondary,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  billSummaryDetails: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  billSummaryDetail: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "15px",
    color: colors.textSecondary,
    borderBottom: `1px dashed ${colors.border}`,
    paddingBottom: "8px",
  },
  detailValue: {
    fontWeight: 600,
    color: colors.textPrimary,
  },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "18px",
    fontWeight: 700,
    color: colors.secondary,
    marginTop: "8px",
    paddingTop: "16px",
    borderTop: `2px solid ${colors.border}`,
  },
  button: {
    padding: "12px",
    fontSize: "16px",
    fontWeight: 700,
    marginTop: "auto",
  },
});
